puts "Seeding birthday question"

question = Question.where(
  title: "What month was this person born?"
).first_or_create

{
  "Albert Wavering"   => "december",
  "Ally Fouts"        => "december",
  "Amanda Ruehlen"    => "june",
  "Andy Rankin"       => "february",
  "Annie Kiley"       => "january",
  "Becca James"       => "may",
  "Becky Tornes"      => "july",
  "Ben Tinsley"       => "june",
  "Ben Eckerson"      => "january",
  "Ben Travis"        => "april",
  "Billy French"      => "february",
  "Blair Culbreth"    => "august",
  "Brandon Dorn"      => "january",
  "Brian Williams"    => "october",
  "Chris Manning"     => "april",
  "Chris Jones"       => "december",
  "Cindy Caldwell"    => "march",
  "Claire Atwell"     => "may",
  "Curt Arledge"      => "january",
  "Dan Tello"         => "october",
  "David Eisinger"    => "september",
  "Elias Fatsi"       => "june",
  "Elliott Muñoz"     => "may",
  "Emily Bloom"       => "february",
  "Grace Canfield"    => "august",
  "Greg Kohn"         => "november",
  "Heather Muety"     => "october",
  "Henry Bley-Vroman" => "december",
  "Ian Brennan"       => "june",
  "Jackson Fox"       => "august",
  "Jason Toth"        => "january",
  "Jeremy Frank"      => "april",
  "Jeremy Fields"     => "july",
  "Josh Korr"         => "january",
  "Justin Sinichko"   => "april",
  "Kaitlyn Irvine"    => "october",
  "Katherine Olvera"  => "april",
  "Kelly Kenny"       => "august",
  "Kevin Vigneault"   => "august",
  "Kevin Powers"      => "november",
  "Khanh Stenberg"    => "december",
  "Laura Sweltz"      => "june",
  "Leo Bauza"         => "october",
  "Megan Zlock"       => "october",
  "Mike Ackerman"     => "november",
  "Mindy Wagner"      => "april",
  "Minh Tran"         => "march",
  "Mitch Daniels"     => "november",
  "Natalie Reich"     => "june",
  "Nate Hunzaker"     => "april",
  "Owen Shifflett"    => "december",
  "Patrick Reagan"    => "august",
  "Pascale Georges"   => "january",
  "Paul Koch"         => "october",
  "Peyton Crump"      => "november",
  "Ryan Stenberg"     => "january",
  "Samantha Freda"    => "july",
  "Samara Strauss"    => "march",
  "Sarah Schraer"     => "june",
  "Solomon Hawk"      => "november",
  "Tom Osborne"       => "march",
  "Trevor Davis"      => "may",
  "Zach Robbins"      => "june",
  "Zachary Porter"    => "april",
}.each do |name, value|
  answer = question.answers.where(title: value).first_or_create
  person = Person.find_by(name: name)

  answer.people << person unless answer.people.include?(person)
end
