puts "Seeding People"

Person.where(name: "Albert Wavering").first_or_create
Person.where(name: "Ally Fouts").first_or_create
Person.where(name: "Amanda Ruehlen").first_or_create
Person.where(name: "Andy Rankin").first_or_create
Person.where(name: "Annie Kiley").first_or_create
Person.where(name: "Becca James").first_or_create
Person.where(name: "Becky Tornes").first_or_create
Person.where(name: "Ben Eckerson").first_or_create
Person.where(name: "Ben Tinsley").first_or_create
Person.where(name: "Ben Travis").first_or_create
Person.where(name: "Billy French").first_or_create
Person.where(name: "Blair Culbreth").first_or_create
Person.where(name: "Brandon Dorn").first_or_create
Person.where(name: "Brian Williams").first_or_create
Person.where(name: "Chris Jones").first_or_create
Person.where(name: "Chris Manning").first_or_create
Person.where(name: "Cindy Caldwell").first_or_create
Person.where(name: "Claire Atwell").first_or_create
Person.where(name: "Curt Arledge").first_or_create
Person.where(name: "Dan Tello").first_or_create
Person.where(name: "David Eisinger").first_or_create
Person.where(name: "Elias Fatsi").first_or_create
Person.where(name: "Elliott Muñoz").first_or_create
Person.where(name: "Emily Bloom").first_or_create
Person.where(name: "Grace Canfield").first_or_create
Person.where(name: "Greg Kohn").first_or_create
Person.where(name: "Heather Muety").first_or_create
Person.where(name: "Henry Bley-Vroman").first_or_create
Person.where(name: "Ian Brennan").first_or_create
Person.where(name: "Jackson Fox").first_or_create
Person.where(name: "Jason Toth").first_or_create
Person.where(name: "Jeremy Fields").first_or_create
Person.where(name: "Jeremy Frank").first_or_create
Person.where(name: "Josh Korr").first_or_create
Person.where(name: "Justin Sinichko").first_or_create
Person.where(name: "Kaitlyn Irvine").first_or_create
Person.where(name: "Katherine Olvera").first_or_create
Person.where(name: "Kelly Kenny").first_or_create
Person.where(name: "Kevin Powers").first_or_create
Person.where(name: "Kevin Vigneault").first_or_create
Person.where(name: "Khanh Stenberg").first_or_create
Person.where(name: "Laura Sweltz").first_or_create
Person.where(name: "Leo Bauza").first_or_create
Person.where(name: "Megan Zlock").first_or_create
Person.where(name: "Mike Ackerman").first_or_create
Person.where(name: "Mindy Wagner").first_or_create
Person.where(name: "Minh Tran").first_or_create
Person.where(name: "Mitch Daniels").first_or_create
Person.where(name: "Natalie Reich").first_or_create
Person.where(name: "Nate Hunzaker").first_or_create
Person.where(name: "Owen Shifflett").first_or_create
Person.where(name: "Pascale Georges").first_or_create
Person.where(name: "Patrick Reagan").first_or_create
Person.where(name: "Paul Koch").first_or_create
Person.where(name: "Peyton Crump").first_or_create
Person.where(name: "Ryan Stenberg").first_or_create
Person.where(name: "Samantha Freda").first_or_create
Person.where(name: "Samara Strauss").first_or_create
Person.where(name: "Sarah Schraer").first_or_create
Person.where(name: "Solomon Hawk").first_or_create
Person.where(name: "Tom Osborne").first_or_create
Person.where(name: "Trevor Davis").first_or_create
Person.where(name: "Zach Robbins").first_or_create
Person.where(name: "Zachary Porter").first_or_create
